### ISSUE TITLE
Público

### ISSUE THREAD

**Issue by guibueno** [guibueno/id-level-easy#2]
Salve, @enricllagostera! Ao passo que eu vou criando conteúdo, seria legal ter uma noção (mesmo que bastante vaga) sobre a galera que vai participar. As dúvidas principais do momento são:
1. Mais ou menos entre ____ e ____ pessoas você chutaria que participariam do evento?
2. Qual o nível médio de conhecimento sobre _design thinking_ que essa galera deve ter?
3. Você diria que o interesse desse pessoal é mais acadêmico (detalhado, teórico) ou prático?
4. Tô imaginando o perfil da galera parecido com o de uma turma de Midialogia. É tipo isso?

Nóis!

**Comment by enricllagostera** [comment]
Fala cara!

Eu diria:

1.Chuto que entre 40 e 60 pessoas. Potencialmente mais.
2. Acho que seria um nível inicial-intermediário. Provavelmente teria de
explicar algum ou outro conceito básico e evitar muito jargão.
3. O interesse provavelmente é mais prático.
4. Eu diria que é parecido, mas não espere um repertório de filmes /
referências tão amplo quanto acaba sendo o caso em Midialogia. Em matéria
de interesses / idade, acho que pode imaginar algo semelhante. :)

Abraço!

**Comment by guibueno** [comment]
Valeu! Abração!
